commit

diff --git a/script/backup-script/dump-postgres b/script/backup-script/dump-postgres
--- a/script/backup-script/dump-postgres
+++ b/script/backup-script/dump-postgres
@@ -7,16 +7,18 @@ PG_USER="postgres"
 DB_NAME="xxxx"  
 BACKUP_DIR="/xx/xx/"
 LOG_DIR="/xx/xx/"
+PG_PASSWORD="your_password_here"
 RETENTION_DAYS=7  # retention backup
 #============================================
+export PGPASSWORD="$PG_PASSWORD"
 TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
 BACKUP_FILE="${BACKUP_DIR}/full_backup_${DB_NAME}_${TIMESTAMP}.sql"
 LOG_FILE="${LOG_DIR}/backup_log_${DB_NAME}_${TIMESTAMP}.log"
 
-# Create directories if not exist
+# create dir
 mkdir -p "$BACKUP_DIR" "$LOG_DIR"
 
-# Function to get current timestamp
+# timestamp
 get_timestamp() {
     date +"%Y-%m-%d %T"
 }
@@ -27,6 +29,20 @@ backup_all() {
     echo "[$ts] ---- START OF BACKUP ----" >> "$LOG_FILE"
     # Dump database to file first
     if ! pg_dumpall -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" --verbose > "$BACKUP_FILE" 2>> "$LOG_FILE"; then
+        ts=$(get_timestamp)
+        echo "[$ts] ---- BACKUP FAILED ----" >> "$LOG_FILE"
+        exit 1
+    fi
+    ts=$(get_timestamp)
+    echo "[$ts] ---- END OF BACKUP ----" >> "$LOG_FILE"
+    echo "[$ts] Backup successful" >> "$LOG_FILE"
+}
+
+backup_dump() {
+    ts=$(get_timestamp)
+    echo "[$ts] ---- START OF BACKUP ----" >> "$LOG_FILE"
+    # Dump database to file first
+    if ! pg_dump -Fp -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" -d "$DB_NAME" --verbose > "$BACKUP_FILE" 2>> "$LOG_FILE"; then
         ts=$(get_timestamp)
         echo "[$ts] ---- BACKUP FAILED ----" >> "$LOG_FILE"
         exit 1
@@ -54,4 +70,5 @@ cleanup_old_backups() {
 # ================== RUN ==================
 check_disk
 backup_all
+#backup_dump
 cleanup_old_backups
